import nodemailer, { type Transporter } from "nodemailer";

import { rankConfig } from "../config";
import { markdownToHtml } from "./markdown-html";

/**
 * Email delivery of the weekly report and the WhatsApp brief.
 *
 * Chosen over WhatsApp automation on purpose: email is official, free, and
 * carries no ToS or account-ban risk. The operator receives both artifacts in
 * their inbox at a fixed time and forwards the brief to the team group by hand -
 * a human in the loop, zero risk.
 *
 * Any SMTP works: a Gmail/Workspace app password, or a transactional service's
 * SMTP endpoint. The transporter is created lazily and reused.
 */

let transporter: Transporter | null = null;

export function isEmailConfigured(): boolean {
  return Boolean(rankConfig.smtpHost && rankConfig.smtpUser && rankConfig.smtpPass && rankConfig.emailTo);
}

export function emailStatus(): { enabled: boolean; configured: boolean; to: string | null; message: string } {
  const configured = isEmailConfigured();
  return {
    enabled: rankConfig.emailEnabled,
    configured,
    to: configured ? rankConfig.emailTo : null,
    message: !rankConfig.emailEnabled
      ? "Email delivery is off (set EMAIL_ENABLED=true)."
      : configured
        ? `Weekly reports will be emailed to ${rankConfig.emailTo}.`
        : "Set SMTP_HOST, SMTP_USER, SMTP_PASS and EMAIL_TO in .env to enable email delivery."
  };
}

function getTransporter(): Transporter {
  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: rankConfig.smtpHost,
      port: rankConfig.smtpPort,
      secure: rankConfig.smtpSecure, // true for 465, false for 587 (STARTTLS)
      auth: { user: rankConfig.smtpUser, pass: rankConfig.smtpPass }
    });
  }
  return transporter;
}

/** Verify the SMTP connection and credentials without sending anything. */
export async function verifyEmail(): Promise<{ ok: boolean; message: string }> {
  if (!isEmailConfigured()) {
    return { ok: false, message: emailStatus().message };
  }
  try {
    await getTransporter().verify();
    return { ok: true, message: `SMTP connection to ${rankConfig.smtpHost} verified.` };
  } catch (error) {
    return { ok: false, message: error instanceof Error ? error.message : "SMTP verification failed." };
  }
}

/**
 * Compose the email HTML: the copy-ready brief up top (a business owner
 * forwards this to WhatsApp), then the full report below.
 */
function renderHtml(clientName: string, period: string, brief: string | null, reportMarkdown: string): string {
  const briefBlock = brief
    ? `<div style="background:#f0fdfa;border:1px solid #99f6e4;border-radius:10px;padding:16px;margin:0 0 24px 0">
         <p style="margin:0 0 8px 0;font-size:11px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;color:#0f766e">Copy this to WhatsApp</p>
         <pre style="white-space:pre-wrap;word-break:break-word;font-family:inherit;font-size:14px;line-height:1.6;color:#134e4a;margin:0">${brief
           .replace(/&/g, "&amp;")
           .replace(/</g, "&lt;")
           .replace(/>/g, "&gt;")}</pre>
       </div>`
    : "";

  return `<!doctype html><html><body style="margin:0;background:#f8fafc;padding:24px;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif">
    <div style="max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;padding:28px">
      <p style="margin:0 0 2px 0;font-size:12px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;color:#0d9488">RankOS weekly report</p>
      <h1 style="margin:0 0 4px 0;font-size:24px;color:#0f172a">${clientName}</h1>
      <p style="margin:0 0 24px 0;font-size:13px;color:#64748b">${period}</p>
      ${briefBlock}
      ${markdownToHtml(reportMarkdown)}
      <p style="margin:28px 0 0 0;font-size:11px;color:#94a3b8;border-top:1px solid #f1f5f9;padding-top:14px">
        Generated by RankOS from Google Search Console data. Every figure is computed before Claude writes the narrative.
      </p>
    </div>
  </body></html>`;
}

export type ReportEmailInput = {
  clientName: string;
  period: string;
  reportMarkdown: string;
  brief: string | null;
  /** Raw files attached so the recipient has the originals too. */
  attachments?: Array<{ filename: string; content: string }>;
};

/** Send one weekly report email. Throws with the SMTP reason on failure. */
export async function sendReportEmail(input: ReportEmailInput): Promise<{ messageId: string }> {
  if (!isEmailConfigured()) {
    throw new Error(emailStatus().message);
  }

  // Plain-text alternative: the brief first (forwardable), then the report as
  // Markdown, so a text-only client still gets everything readable.
  const text = [
    input.brief ? `--- WhatsApp brief (copy this) ---\n\n${input.brief}\n` : "",
    `--- Full report ---\n\n${input.reportMarkdown}`
  ]
    .filter(Boolean)
    .join("\n");

  const info = await getTransporter().sendMail({
    from: rankConfig.emailFrom,
    to: rankConfig.emailTo,
    subject: `${input.clientName} - Weekly SEO report (${input.period})`,
    text,
    html: renderHtml(input.clientName, input.period, input.brief, input.reportMarkdown),
    attachments: input.attachments?.map((file) => ({ filename: file.filename, content: file.content }))
  });

  return { messageId: info.messageId };
}

/** A small self-test email, for the "send test now" button. */
export async function sendTestEmail(): Promise<{ messageId: string }> {
  return sendReportEmail({
    clientName: "RankOS",
    period: "test",
    brief: "*RankOS test* - if you can read this in your inbox, weekly report delivery is working. Forward-ready briefs will arrive here every week.",
    reportMarkdown:
      "## Email delivery is working\n\nThis is a test from RankOS. Your real weekly reports will arrive at this address, each with the copy-ready WhatsApp brief at the top and the full report below."
  });
}
